"""migration_3

Revision ID: 08a85fd8de03
Revises: d6bf7d91b8ba
Create Date: 2023-12-06 16:37:45.371644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08a85fd8de03'
down_revision: Union[str, None] = 'd6bf7d91b8ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_foreign_key(None, 'order_tests', 'customers', ['customer_id'], ['customer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_tests', type_='foreignkey')
    op.drop_table('customers')
    # ### end Alembic commands ###
