"""миграция для ткстов4

Revision ID: 8020a2931cf4
Revises: c23cafd1c8ef
Create Date: 2023-12-13 16:35:43.003762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8020a2931cf4'
down_revision: Union[str, None] = 'c23cafd1c8ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
