"""миграция для ткстов8

Revision ID: 08956c5d593b
Revises: f6614bfdbfd3
Create Date: 2023-12-14 09:10:53.313807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08956c5d593b'
down_revision: Union[str, None] = 'f6614bfdbfd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
