"""дороботка модели order

Revision ID: a958001f1ddb
Revises: dab1e5c52aa4
Create Date: 2023-12-16 11:47:54.537504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a958001f1ddb'
down_revision: Union[str, None] = 'dab1e5c52aa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('product_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('store_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'stores', ['store_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'store_id')
    op.drop_column('orders', 'quantity')
    op.drop_column('orders', 'product_id')
    # ### end Alembic commands ###
