"""миграция для тестов 3

Revision ID: c23cafd1c8ef
Revises: 3d6d2b47114d
Create Date: 2023-12-13 16:18:40.196103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c23cafd1c8ef'
down_revision: Union[str, None] = '3d6d2b47114d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
