"""миграция для тестов 7

Revision ID: f6614bfdbfd3
Revises: f34534ab9090
Create Date: 2023-12-14 09:08:32.628674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6614bfdbfd3'
down_revision: Union[str, None] = 'f34534ab9090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
